CREATE TABLE IF NOT EXISTS sis (
    session_token TEXT PRIMARY KEY,
    a TEXT NOT NULL,
    x TEXT NOT NULL,
    c TEXT NOT NULL
)WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS ois (
    session_token TEXT PRIMARY KEY,
    a TEXT NOT NULL,
    x TEXT NOT NULL,
    c TEXT NOT NULL
)WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS msis (
    session_token TEXT PRIMARY KEY,
    a TEXT NOT NULL,
    x TEXT NOT NULL,
    c TEXT NOT NULL
)WITHOUT ROWID;